/* Bundles assets/locales/{en,ar,fr}.json into assets/locales/locales.js.

   The site has to open straight off disk (file://), where fetch() is blocked, so
   the dictionaries are inlined as a plain script. Run this after editing any
   locale JSON — nothing else regenerates it.

   Run: node tools/build-locales.mjs */

import { readFileSync, writeFileSync } from "node:fs";

const LANGS = ["en", "ar", "fr"];
const OUT = "assets/locales/locales.js";

const dicts = {};
for (const lang of LANGS) {
  dicts[lang] = JSON.parse(readFileSync(`assets/locales/${lang}.json`, "utf8"));
}

/* Every language must carry the same key set, or a switch to AR/FR silently
   leaves English text (or blank nodes) behind. */
function keys(obj, prefix = "") {
  return Object.entries(obj).flatMap(([k, v]) =>
    v && typeof v === "object" && !Array.isArray(v)
      ? keys(v, `${prefix}${k}.`)
      : [`${prefix}${k}`]
  );
}
const enKeys = new Set(keys(dicts.en));
let problems = 0;
for (const lang of LANGS.slice(1)) {
  const theseKeys = new Set(keys(dicts[lang]));
  const missing = [...enKeys].filter(k => !theseKeys.has(k));
  const extra = [...theseKeys].filter(k => !enKeys.has(k));
  if (missing.length) { console.warn(`  ${lang}: missing ${missing.length} key(s): ${missing.join(", ")}`); problems++; }
  if (extra.length) { console.warn(`  ${lang}: ${extra.length} key(s) not in en: ${extra.join(", ")}`); problems++; }
}

const banner = "/* generated by tools/build-locales.mjs from en/ar/fr.json — do not hand-edit.\n"
  + "   Inlined so the site runs from file://, where fetch() is blocked. */\n";

writeFileSync(OUT, (banner + `window.DH_LOCALES = ${JSON.stringify(dicts)};\n`).replace(/\n/g, "\r\n"));

console.log(`${OUT} written (${LANGS.join(", ")})`);
console.log(problems ? `${problems} parity warning(s) above.` : "All three languages have matching keys.");
