"""Builds the 32-tooth coordinate map for the booking calendar.

Why this is hand-anchored rather than fully detected: colour thresholding
separates teeth from gum and lip cleanly, but the tongue's pale upper surface
passes the same test, so automated lower-arch cells kept landing on the tongue.
Meanwhile the site already contains nine verified tooth boxes — the six nav
teeth and three language teeth, positioned by hand and in production — which are
far better ground truth than a threshold.

So: the six upper anchors are used verbatim, the rest are extrapolated outward
along each arch (teeth get smaller, higher and tighter toward the molars), and
the right side is mirrored from the left about the midline so the arch stays
symmetric. tools/measure-teeth.py renders a preview to check the result against
the actual image.

    python tools/build-teeth-map.py --preview
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "data" / "teeth.json"
SRC = ROOT / "assets" / "media" / "mouth-open.jpg"

IMG_W, IMG_H = 1344, 752

# ── upper arch ──────────────────────────────────────────────────────────────
# The six front teeth are the live nav teeth, copied exactly from the pages.
UPPER_ANCHORS = [
    (35.19, 13.87, 2.30, 7.37),
    (39.02, 11.04, 3.21, 7.04),
    (43.97,  9.63, 4.98, 7.60),
    (51.04,  9.63, 4.98, 7.60),
    (57.77, 11.16, 3.21, 6.93),
    (62.49, 13.99, 2.25, 7.26),
]
# Five more per side, receding up and back toward the molars.
UPPER_LEFT_EXTRA = [
    # Tiled along the arch from the last anchor (35.19) back to 28.6, which is
    # where the upper molars actually end in this render. Unlike the lower arch,
    # the upper molars genuinely are narrow here — they recede behind the arch —
    # so these stay slim rather than being widened to match the lower ones.
    (33.55, 14.20, 1.64, 7.60),   # 1st premolar
    (32.05, 17.60, 1.50, 7.30),   # 2nd premolar
    (30.70, 21.00, 1.35, 7.00),   # 1st molar
    (29.55, 24.40, 1.15, 6.50),   # 2nd molar
    (28.60, 27.60, 0.95, 5.90),   # 3rd molar
]

# ── lower arch ──────────────────────────────────────────────────────────────
# Left half only, centre outward; the three language teeth sit at top ~78%,
# which fixes the front of this arch.
LOWER_LEFT = [
    # Measured the same way. The earlier values tapered these to ~1.8% wide, as
    # if seen from the side; in this frontal render the lower molars are nearly
    # as wide as the front teeth, which is why the dates sat on the gum.
    (46.20, 77.90, 3.90, 7.50),   # central incisor
    (42.30, 77.20, 3.90, 7.30),   # lateral incisor
    (39.00, 76.40, 3.30, 6.00),   # canine
    (35.60, 73.80, 3.40, 5.00),   # 1st premolar
    (33.50, 69.60, 4.00, 4.50),   # 2nd premolar
    (32.00, 64.70, 4.30, 4.80),   # 1st molar
    (30.80, 57.00, 5.00, 7.50),   # 2nd molar
    (30.00, 48.50, 5.30, 8.30),   # 3rd molar
]


def mirror(t):
    left, top, w, h = t
    return (round(100 - left - w, 2), top, w, h)


def build():
    upper = sorted(UPPER_LEFT_EXTRA + UPPER_ANCHORS
                   + [mirror(t) for t in UPPER_LEFT_EXTRA],
                   key=lambda t: t[0])
    lower = sorted(LOWER_LEFT + [mirror(t) for t in LOWER_LEFT],
                   key=lambda t: t[0])

    teeth = []
    for arch, rows in (("upper", upper), ("lower", lower)):
        for i, (left, top, w, h) in enumerate(rows):
            teeth.append({
                "arch": arch, "index": i,
                "left": round(left, 2), "top": round(top, 2),
                "width": round(w, 2), "height": round(h, 2),
            })
    return teeth


def main():
    teeth = build()
    upper = [t for t in teeth if t["arch"] == "upper"]
    lower = [t for t in teeth if t["arch"] == "lower"]

    print(f"upper {len(upper)}   lower {len(lower)}   total {len(teeth)}")
    if len(teeth) != 32:
        print(f"!! expected 32, got {len(teeth)}")
    print()
    for t in teeth:
        print(f"  {t['arch']:5} #{t['index']:2}  left {t['left']:6.2f}  top {t['top']:6.2f}  "
              f"w {t['width']:5.2f}  h {t['height']:5.2f}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({
        "source": "assets/media/mouth-open.jpg",
        "imageWidth": IMG_W, "imageHeight": IMG_H,
        "note": ("Percentages of the stage image, the unit .tooth already uses. "
                 "Generated by tools/build-teeth-map.py. The six upper front "
                 "teeth are the live nav tooth coordinates; the rest extrapolate "
                 "along each arch and mirror about the midline."),
        "count": len(teeth),
        "teeth": teeth,
    }, indent=2) + "\n", encoding="utf-8")
    print(f"\nwrote {OUT.relative_to(ROOT)}")

    if "--preview" in sys.argv:
        from PIL import Image, ImageDraw
        im = Image.open(SRC).convert("RGB")
        w, h = im.size
        d = ImageDraw.Draw(im)
        for t in teeth:
            x0 = t["left"] / 100 * w
            y0 = t["top"] / 100 * h
            x1 = x0 + t["width"] / 100 * w
            y1 = y0 + t["height"] / 100 * h
            colour = (220, 30, 30) if t["arch"] == "upper" else (0, 110, 255)
            d.rectangle([x0, y0, x1, y1], outline=colour, width=3)
            d.text((x0 + 2, y0 + 2), str(t["index"] + 1), fill=colour)
        path = ROOT / "preview" / "teeth-map.png"
        path.parent.mkdir(parents=True, exist_ok=True)
        im.save(path)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
