/* One-off/idempotent patcher: gives every page the same <head> block
   (canonical, hreflang, Open Graph, Twitter, favicon, JSON-LD) and fixes the
   loader <video> markup. Re-running it is safe — it replaces its own block.

   Run: node tools/patch-heads.mjs
   The site URL is the token SITE_URL below; swap it with tools/set-domain.mjs. */

import { read, write } from "./lib/edit.mjs";

const SITE_URL = "https://joshrhousary.github.io/dr-husseini-dental";
const BEGIN = "<!-- dh:head:begin — generated by tools/patch-heads.mjs, do not hand-edit -->";
const END = "<!-- dh:head:end -->";

/** page file -> { path on the site, og type } */
const PAGES = {
  "index.html":     { url: "/",             type: "website" },
  "about.html":     { url: "/about.html",    type: "profile" },
  "services.html":  { url: "/services.html", type: "website" },
  "booking.html":   { url: "/booking.html",  type: "website" },
  "contact.html":   { url: "/contact.html",  type: "website" },
  "blog.html":      { url: "/blog.html",     type: "website" },
  "blog/post.html": { url: "/blog/post.html", type: "article" }
};

const PRACTICE = {
  name: "Dr. Jihad S. Husseini",
  tagline: "Cosmetic · Endodontic · Implant Dentistry",
  clinicPhone: "+96101308206",
  mobilePhone: "+96103855860"
};

function head(file, { url, type }, title, description, depth) {
  const base = "../".repeat(depth) || "";
  const abs = SITE_URL + url;
  // The Dentist block is the practice itself and is identical on every page;
  // address/openingHours stay out until the client supplies them — a placeholder
  // address in structured data is worse than none.
  const ld = {
    "@context": "https://schema.org",
    "@type": "Dentist",
    name: PRACTICE.name,
    description: PRACTICE.tagline,
    url: SITE_URL + "/",
    telephone: [PRACTICE.clinicPhone, PRACTICE.mobilePhone],
    image: SITE_URL + "/assets/media/mouth-open.jpg",
    medicalSpecialty: "Dentistry",
    availableService: [
      { "@type": "MedicalProcedure", name: "Cosmetic dentistry" },
      { "@type": "MedicalProcedure", name: "Endodontics" },
      { "@type": "MedicalProcedure", name: "Prosthetic and implant dentistry" }
    ],
    areaServed: { "@type": "Country", name: "Lebanon" },
    availableLanguage: ["en", "ar", "fr"]
    // TODO(client): add "address" (PostalAddress) and "openingHoursSpecification".
  };

  return [
    BEGIN,
    `<link rel="canonical" href="${abs}">`,
    `<link rel="alternate" hreflang="en" href="${abs}">`,
    `<link rel="alternate" hreflang="ar" href="${abs}">`,
    `<link rel="alternate" hreflang="fr" href="${abs}">`,
    `<link rel="alternate" hreflang="x-default" href="${abs}">`,
    `<meta name="robots" content="index,follow">`,
    `<link rel="alternate" type="application/rss+xml" title="${PRACTICE.name} — Blog" href="${SITE_URL}/feed.xml">`,
    `<meta name="theme-color" content="#0F5C56">`,
    `<link rel="icon" href="${base}assets/media/favicon.svg" type="image/svg+xml">`,
    `<link rel="apple-touch-icon" href="${base}assets/media/mouth-open.jpg">`,
    `<meta property="og:site_name" content="${PRACTICE.name}">`,
    `<meta property="og:type" content="${type}">`,
    `<meta property="og:url" content="${abs}">`,
    `<meta property="og:title" content="${title}">`,
    `<meta property="og:description" content="${description}">`,
    `<meta property="og:image" content="${SITE_URL}/assets/media/mouth-open.jpg">`,
    `<meta property="og:image:width" content="1344">`,
    `<meta property="og:image:height" content="752">`,
    `<meta property="og:locale" content="en_US">`,
    `<meta property="og:locale:alternate" content="ar_LB">`,
    `<meta property="og:locale:alternate" content="fr_FR">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${title}">`,
    `<meta name="twitter:description" content="${description}">`,
    `<meta name="twitter:image" content="${SITE_URL}/assets/media/mouth-open.jpg">`,
    `<script type="application/ld+json">${JSON.stringify(ld)}</script>`,
    END
  ].join("\n");
}

const attr = (html, re) => (html.match(re) || [, ""])[1];

let changed = 0;
for (const [file, meta] of Object.entries(PAGES)) {
  let html = read(file);
  const before = html;
  const depth = (file.match(/\//g) || []).length;
  const base = "../".repeat(depth) || "";

  const title = attr(html, /<title>([\s\S]*?)<\/title>/).trim();
  const description = attr(html, /<meta name="description" content="([^"]*)"/);
  const block = head(file, meta, title, description, depth);

  // 1. head block — replace an existing generated block, else insert after <meta name="description">
  if (html.includes(BEGIN)) {
    html = html.replace(new RegExp(`${BEGIN}[\\s\\S]*?${END}`), block);
  } else {
    html = html.replace(
      /(<meta name="description"[^>]*>)/,
      `$1\n${block}`
    );
  }

  // 2. loader <video>: poster was an absolute "/assets/..." path, which 404s on
  //    file:// and from the blog/ subdirectory. Ship the 720p source and let
  //    main.js upgrade to 1080p on a wide, fast client.
  html = html.replace(
    /<video class="loader-video"[\s\S]*?<\/video>/,
    `<video class="loader-video" muted playsinline preload="none" poster="${base}assets/media/mouth-closed.jpg" data-hq="${base}assets/media/loader-1080.mp4"><source src="${base}assets/media/loader-720.mp4" type="video/mp4"></video>`
  );

  if (write(file, html)) { changed++; console.log("patched", file); }
  else console.log("unchanged", file);
}
console.log(`\n${changed} file(s) written.`);
